import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:gundam_pos/data/print_format_store.dart';
import 'package:gundam_pos/logic/money.dart' as money;
import 'package:gundam_pos/logic/print_format.dart';
import 'package:gundam_pos/logic/print_format_render.dart';
import 'package:gundam_pos/logic/print_payload.dart';
import 'package:gundam_pos/services/print_broker.dart';

/// PARITY guard: the tablet must SUPPLY every print token the server registry
/// declares for a ticket type — or explicitly mark it intentionally-empty with a
/// reason. The server vocabulary is exported to `tool/print-tokens.json`
/// (generated by web/tests/print-token-parity.test.ts); a token the server adds
/// but the POS forgets fails HERE instead of printing a literal `{token}` to a
/// customer.
///
/// Refresh the manifest from the web side:
///   UPDATE_PRINT_TOKENS=1 npx vitest run tests/print-token-parity.test.ts
const String kManifestPath = 'tool/print-tokens.json';

/// Item-line tokens resolved from the ticket's item ROWS (ITEM_LIST / TABLE),
/// never the global token map — the builder ships them under `items`.
const Set<String> kRowScopedItemTokens = {
  'item_name',
  'item_qty',
  'item_price',
  'item_line_total',
  'modifier_name',
  'modifier_price',
  'modifier_qty',
};

/// Payment tokens resolved from the ticket's payment ROWS (PAYMENT_LINES).
const Set<String> kRowScopedPaymentTokens = {
  'payment_method',
  'payment_amount',
  'payment_reference',
  'payment_tendered',
  'split_index',
};

/// Tokens the POS can never source on a tablet ticket, with the REASON. They are
/// still shipped as EMPTY strings by [TicketContext.tokens] so a show_if_present
/// block skips instead of printing the literal — but they are listed here so the
/// parity test can tell "deliberately empty" apart from "someone forgot".
const Map<String, String> kIntentionallyEmptyTokens = {
  'legal_footer': 'no per-outlet legal-footer field on the tenant yet',
  'custom_1': 'no per-outlet custom slot source yet',
  'custom_2': 'no per-outlet custom slot source yet',
  'custom_3': 'no per-outlet custom slot source yet',
  'custom_4': 'no per-outlet custom slot source yet',
  'shipment_description': 'the POS shipment path ships amounts only, not a description',
  'void_reason': 'void is a web-app only action; the POS never prints it',
  'refund_amount': 'refund is a web-app only action; the POS never prints it',
  'refund_reason': 'refund is a web-app only action; the POS never prints it',
  'approval_status': 'approval decisions live in the web-app',
  'requester_name': 'approval requests live in the web-app',
  'approver_name': 'approval decisions live in the web-app',
  'approval_acted_at': 'approval decisions live in the web-app',
};

List<PrintItem> _items() => [
      PrintItem(
        name: 'Flat White',
        itemId: 'i1',
        qty: 2,
        unitPrice: 38000,
        lineTotal: 76000,
        priceLevelLabel: 'Regular',
        modifiers: [PrintModifier(name: 'Oat', price: 8000, qty: 1)],
      ),
    ];

TicketContext _ctx({String type = 'BILL'}) => TicketContext(
      storeName: 'Northstar Central',
      storeShortcode: 'NSC',
      storeAddress: 'Jl. Sudirman 18, Jakarta',
      storePhone: '021-5578899',
      storeSocial: '@northstar',
      groupName: 'Nusantara Hospitality Group',
      groupShortcode: 'NHG',
      cashier: 'Rina',
      tableName: 'A1',
      guestName: 'Maya',
      ticketType: type,
      deviceShortcode: 'NSTAR-POS1',
      deviceLabel: 'Counter 1',
      posClientId: 'dev-01',
      formatName: 'Default Bill 80mm',
      formatVersion: '3',
      currencyLabel: 'IDR',
      timezone: 'Asia/Jakarta',
      pax: '3',
      openedAt: '2026-09-28 10:31:00',
      openedBy: 'Rina',
      closedBy: 'Rangga',
      at: DateTime(2026, 9, 28, 10, 42, 0),
    );

List<String> _tokens(Map<String, dynamic> payload) =>
    ((payload['tokens'] as Map).keys).cast<String>().toList();

void main() {
  final manifest = jsonDecode(File(kManifestPath).readAsStringSync()) as Map<String, dynamic>;
  final params = (manifest['params'] as List).cast<Map<String, dynamic>>();

  List<Map<String, dynamic>> declaredFor(String type) =>
      params.where((p) => (p['ticketTypes'] as List).contains(type)).toList();

  test('manifest exists and is non-trivial (generated from the server registry)', () {
    expect(params.length, greaterThan(50));
    expect((manifest['ticketTypes'] as List), contains('BILL'));
  });

  const builder = TicketPayloadBuilder();
  final flow = money.computeMoneyFlow(
    [money.MoneyLine(subtotal: 76000)],
    0,
    0,
    money.RoundingMode.none,
  );
  final split = money.finalizePayments(
    flow.total,
    [money.PaymentInput(outletMethodId: 'm1', type: money.PayType.cash, amount: flow.total)],
  );

  group('BILLISH tickets supply every declared token', () {
    for (final type in const ['BILL', 'RECEIPT_COPY', 'CANCELED_ORDER']) {
      test(type, () {
        final ctx = _ctx(type: type);
        final payload = type == 'CANCELED_ORDER'
            ? builder.canceledOrder(ctx: ctx, items: _items())
            : builder.bill(
                ctx: ctx,
                items: _items(),
                receiptId: 'NSC-20260928-1042-0000007',
                flow: flow,
                split: split,
                settled: true,
              );
        final keys = _tokens(payload).toSet();
        for (final p in declaredFor(type)) {
          final token = p['token'] as String;
          if (kRowScopedItemTokens.contains(token) || kRowScopedPaymentTokens.contains(token)) {
            continue; // supplied by the item/payment rows
          }
          final known = keys.contains(token) || kIntentionallyEmptyTokens.containsKey(token);
          expect(known, isTrue,
              reason: 'declared $type token "$token" is neither supplied by the POS nor '
                  'listed in kIntentionallyEmptyTokens');
        }
      });
    }
  });

  group('CAPISH tickets supply every declared token', () {
    test('CAPTAIN_ORDER', () {
      final ctx = _ctx(type: 'CAPTAIN_ORDER');
      final payload = builder.captainOrder(ctx: ctx, items: _items());
      final keys = _tokens(payload).toSet();
      for (final p in declaredFor('CAPTAIN_ORDER')) {
        final token = p['token'] as String;
        if (kRowScopedItemTokens.contains(token) || kRowScopedPaymentTokens.contains(token)) continue;
        expect(keys.contains(token) || kIntentionallyEmptyTokens.containsKey(token), isTrue,
            reason: 'declared CAPTAIN_ORDER token "$token" unaccounted for');
      }
    });

    test('BEV_LABEL', () {
      final ctx = _ctx(type: 'BEV_LABEL');
      final payload = builder.bevLabel(ctx: ctx, item: _items().first);
      final keys = _tokens(payload).toSet();
      for (final p in declaredFor('BEV_LABEL')) {
        final token = p['token'] as String;
        if (kRowScopedItemTokens.contains(token) || kRowScopedPaymentTokens.contains(token)) continue;
        expect(keys.contains(token) || kIntentionallyEmptyTokens.containsKey(token), isTrue,
            reason: 'declared BEV_LABEL token "$token" unaccounted for');
      }
    });
  });

  test('(a) store_address / store_social / group_name carry the outlet values (preview AND print)', () {
    final payload = builder.bill(
      ctx: _ctx(),
      items: _items(),
      receiptId: 'NSC-1',
      flow: flow,
      split: split,
      settled: true,
    );
    final t = payload['tokens'] as Map;
    expect(t['store_address'], 'Jl. Sudirman 18, Jakarta');
    expect(t['store_phone'], '021-5578899');
    expect(t['store_social'], '@northstar');
    expect(t['group_name'], 'Nusantara Hospitality Group');
    expect(t['group_shortcode'], 'NHG');
    expect(t['store_shortcode'], 'NSC');

    // The values ACTUALLY render (server style) — not just present in the map.
    final fmt = PrintFormat.fromJson({
      'formatId': 'bill-tokens',
      'name': 'Tokens',
      'ticketType': 'BILL',
      'version': 1,
      'widthMm': 80,
      'blocks': [
        {'id': 'a', 'type': 'VAR', 'param': '{store_address}'},
        {'id': 'b', 'type': 'VAR', 'param': '{store_social}'},
        {'id': 'c', 'type': 'VAR', 'param': '{group_name}'},
      ],
    });
    final text = renderPrintFormat(format: fmt, ticketPayload: payload).lines.join('\n');
    expect(text, contains('Jl. Sudirman 18, Jakarta'));
    expect(text, contains('@northstar'));
    expect(text, contains('Nusantara Hospitality Group'));

    // Preview ≡ print: the SAME payload through both engines yields one text.
    final store = PrintFormatStore()
      ..apply([
        {
          'formatId': 'bill-tokens',
          'name': 'Tokens',
          'ticketType': 'BILL',
          'version': 1,
          'widthMm': 80,
          'blocks': [
            {'id': 'a', 'type': 'VAR', 'param': '{store_address}'},
            {'id': 'b', 'type': 'VAR', 'param': '{store_social}'},
            {'id': 'c', 'type': 'VAR', 'param': '{group_name}'},
          ],
        },
      ]);
    final viaBroker = PrintBroker(
      store: store,
      queue: PrintQueue(transport: _NullTransport()),
    ).renderTicket(ticketType: 'BILL', payload: payload, widthMm: 80);
    expect(viaBroker.lines.join('\n'), text);
  });

  test('(b) voucher_name / voucher_amount fill when a voucher is applied', () {
    final payload = builder.bill(
      ctx: _ctx(),
      items: _items(),
      receiptId: 'NSC-1',
      flow: flow,
      split: split,
      settled: true,
      voucherName: 'WELCOME50',
      voucherAmount: 5000,
      discountAmount: 0,
    );
    final t = payload['tokens'] as Map;
    expect(t['voucher_name'], 'WELCOME50');
    expect(t['voucher_amount'], 5000);
    expect(t['discount_name'], '');
    expect(t['discount_amount'], 0);
  });

  test('(b2) discount_name fills and voucher stays empty for a discount', () {
    final payload = builder.bill(
      ctx: _ctx(),
      items: _items(),
      receiptId: 'NSC-1',
      flow: flow,
      split: split,
      settled: true,
      discountName: 'Staff 10%',
      discountAmount: 7600,
    );
    final t = payload['tokens'] as Map;
    expect(t['discount_name'], 'Staff 10%');
    expect(t['discount_amount'], 7600);
    expect(t['voucher_name'], '');
    expect(t['voucher_amount'], 0);
  });

  test('unpaid preview sends paid/change/payment as EMPTY, never absent-as-literal', () {
    final payload = builder.bill(
      ctx: _ctx(),
      items: _items(),
      receiptId: 'NSC-1',
      flow: flow,
      settled: false, // split omitted
      paidAt: DateTime(2026, 9, 28, 10, 42, 0),
    );
    final t = payload['tokens'] as Map;
    for (final k in ['paid_at', 'paid_amount', 'change', 'tips_amount', 'payment_type']) {
      expect(t.containsKey(k), isTrue, reason: '$k must be present (empty), not absent');
      expect(t[k], '');
    }
    expect((payload['payments'] as List), isEmpty);
  });
}

class _NullTransport implements PrintTransport {
  @override
  Future<void> send(PrintJob job) async {}
}
